[package]
name = "hb-cgi"
version = "0.1.0"
edition = "2024"

[dependencies]
cgi = "0.8.0"
handlebars = "6.3.2"
http = "1.3.1"
reqwest = { version = "0.12.24", features = ["json", "blocking"] }
serde_json = "1.0.145"
url = "2.5.7"
