[package]
name = "hb-cgi"
version = "0.1.0"
edition = "2024"

[dependencies]
cgi = "0.8.0"
handlebars = "6.3.2"
http = "1.3.1"
serde = "1.0.228"
serde_json = "1.0.145"
ureq = { version = "3.1.2", features = ["json"] }
url = "2.5.7"
